<?php
/**
 * @file Provides phone-based callback functionality for VozMob
 */ 

/**
 * Call the specified number and execute the callback script
 */
function vozmob_callback_dial($number, $script_name='vozmob_callback_record_script'){

  global $user;

  // Create new voipcall node for the callback 
  $details['dest_number'] = $number;
  $details['dest_name'] = $user->name;
  $details['caller_name'] = 'callblast message recorder';

  // load voip script
  $vars = array('uid' => $user->uid, 'name' => $name, 'number' => $number);
  $script = VoipScript::loadScript($script_name, $vars);
  $details['script'] = $script;
  $voipcall_node = voipcall_save($details);

  // Dial the call.
  voip_dial($voipcall_node);

$message = t("New callback dialed for $user->name. See voipcall nid $voipcall_node->nid");
watchdog('vozmob_callback', $message);

}


/**
 * Implementation of hook_voipscript_load_script()
 */
function vozmob_callback_voipscript_load_script($script_name, $vars=NULL) {
  $script = NULL;
  if($script_name == 'vozmob_callback_record_script') {
    $script = _vozmob_callback_get_record_script($vars);
  }

  return $script;
}


function _vozmob_callback_get_record_script($vars) {
  $script = new VoipScript('vozmob_callback_record_script');

  $script->addLabel('start');
  $script->addSay("Please record your message after the beep.  When done, press the pound key.");
  $timeout = 5;
  $end_key = '#';
  $max_length = 20;
  $script->addRecord($timeout, $end_key, $max_length);

  $script->addSay('You said ');
  $script->addPlay('%recording_url');

  $script->addLabel('accept menu');
  $text = "To accept this recording, press 1.  To record it once again, press 2. To hangup, press the pound key.";
  $url = '';
  $timeout = 5;
  $end_key = '';
  $num_digits = 1;
  $script->addGetInput($text, $url, $timeout, $end_key, $num_digits);

  $script->addGotoIf('accept recording', "^%input_digits == '1'");

  $script->addGotoIf('start', "^%input_digits == '2'");

  $script->addGotoIf('end call', "^%input_digits == '#'");

  $script->addSay('Invalid input received. Please try again.');
  $script->addGoto('accept menu');

  $script->addLabel('accept recording');
  $script->addSet('uid', $vars['uid']);
  $script->addSet('name', $vars['name']);
  $script->addSet('number', $vars['number']);
  // Process recording.
  $script->addSay('About to start processing the recorded file.');
  $script->addSet('callback_result',
        '^_vozmob_callback_record_callback(%call_id, %recording_url, %recording_duration, %uid, %name, %number)');
  $script->addSay('The callback returned: %callback_result');
  $script->addGoto('end call');

  $script->addLabel('no input received');
  $script->addSay("No input received. Please try again.");
  $script->addGoto('start');

  $script->addLabel('end call');
  $script->addSay('Bye bye.');
  $script->addHangup();

  return $script;
}

/**
 * Callback function associated with the script vozmob_callback_record_script.
 * It is called whenever that script records a new entry from the user.
 */
function _vozmob_callback_record_callback($call_id, $recording_url, $recording_duration, $uid, $name, $number) {
watchdog('vozmob_callback', "in _vozmob_callback_record_callback($call_id, $recording_url, $recording_duration, $uid, $name, $number)");

  $message = t("New callback message recorded :: call_id: $call_id, recording_url: $recording_url, recording_duration: $recording_duration, uid: $uid, name: $name, number: $number");
  watchdog(vozmob_callback, $message);



  return 'Success';
}


